version: '3.8'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
#    command: 'sh php artisan migrate && php artisan serve --host=0.0.0.0'
    command: 'sh -c ./run.sh'
    volumes:
      - .:/app
    ports:
      - 8001:8000
    depends_on:
      - main_db

  main_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33064:3306
